# Generated by Django 2.1.5 on 2019-02-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_size_image',
            field=models.ImageField(db_column='full_size_image', default='default.jpg', upload_to='profile_pics'),
        ),
    ]
