# Generated by Django 2.1.5 on 2019-02-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_full_size_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_size_image',
        ),
    ]
